-- CreateEnum
CREATE TYPE "PointsChoice" AS ENUM ('WHISKY_KRACHTIG', 'WHISKY_MEDIUM', 'WHISKY_MILD', 'WHISKY_VOL', 'WHISKY_ARTIKEL', 'KORTING_WEEKEND', 'KORTING_KLEDING', 'DUURDERE_FLES');

-- AlterTable
ALTER TABLE "Member" ADD COLUMN "pointsChoice" "PointsChoice";
ALTER TABLE "Member" ADD COLUMN "pointsFollowUp" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Member" DROP COLUMN "pointsNote";
